core/urls.py
from django.urls import path
from . import views

app_name = "gold"
urlpatterns = [
    path("", views.home, name="home"),
    path("reset", views.reset, name="reset"),
    path("process_money", views.process_money, name="process")
]

ninja_gold/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls")), 
    #path('admin/', admin.site.urls),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import redirect, render
import random
from datetime import datetime

# Create your views here.
def home(request):
    if "gold" not in request.session or 'log' not in request.session:
        request.session["gold"] = 0
        request.session["log"] = []
        request.session["log"].append("Welcome!!! " + "(" + str(datetime.now().strftime("%Y-%m-%d %H:%M:%S")) + ")")
        request.session["count"] = 0
    return render(request, "index.html")

def reset(request):
    request.session.flush()
    return redirect("/")

def process_money(request):
    if request.method == "GET":
        return redirect("/")
    elif request.method == "POST":
        request.session["count"] += 1
        if request.POST["farming"] == "farm":
            gold = random.randint(10,20)
            request.session["log"].append("Earned " + str(gold) + " gold from the farm! " + "(" + str(datetime.now().strftime("%Y-%m-%d %H:%M:%S")) + ")")
        if request.POST["farming"] == "cave":
            gold = random.randint(5,10)
            request.session["log"].append("Earned " + str(gold) + " golds from the cave! " + "(" + str(datetime.now().strftime("%Y-%m-%d %H:%M:%S")) + ")")
        if request.POST["farming"] == "house":
            gold = random.randint(2,5)
            request.session["log"].append("Earned " + str(gold) + " golds from the house! " + "(" + str(datetime.now().strftime("%Y-%m-%d %H:%M:%S")) + ")")
        if request.POST["farming"] == "casino":
            gold = random.randint(-50,50)
            if gold > 0:
                request.session["log"].append("Entered a casino and win " + str(gold) + " golds... Congrats!!!" + "(" + str(datetime.now().strftime("%Y-%m-%d %H:%M:%S")) + ")")
            else:
                request.session["log"].append("Entered a casino and lost " + str(gold)[1:] + " golds... Ouch!!!!" + "(" + str(datetime.now().strftime("%Y-%m-%d %H:%M:%S")) + ")")
        
        request.session["gold"] += gold

        if request.session["gold"] >= 100:
            return render(request, "win.html")

        if request.session["gold"] <= -20:
            return render(request, "lost.html")

        
        ## logeando en consola los datos del post
        #for key, value in request.POST.items():
        #    print(f'Key: %s' % (key) ) 
        #    print(f'Value %s' % (value) )
        
        return redirect("/")
    

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es-CL">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Mi primer template Django + Bootstrap">
    <meta name="author" content="Mauricio Abarca">
    <meta name="keywords" content="actividad, curso, ejercicio, html, css, bootstrap, Django">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- Mi CSS-->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body class="bg-secondary">
    <div class="wrapper">
        <div class="container-fluid p-3">
            {% block header %}{% endblock %}
            {% block subheader %}{% endblock %}
            {% block content %}{% endblock %}
        </div>

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>
</html>

core/templates/index.html
{% extends "base.html" %}
{% block title %}Ninja Gold{% endblock %}
{% block header %}{% endblock %}
{% block subheader %}{% endblock %}
{% block content %}
<div class="container mt-3">
    <div class="row">
        <div class="col mb-2">
            <h2 class="text-light">Your gold: <span class="text-warning">{{request.session.gold}}</span></h2>
        </div>
        <div class="col text-end">
            <a href="{% url 'gold:reset' %}" class="btn btn-light">Play Again</a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-3 mb-2">
            <form action="{% url 'gold:process' %}" method="POST">
                {% csrf_token %}
                <div class="card text-center">
                    <div class="card-header text-white bg-success">
                        <h4 class="card-title">Farm</h4>
                    </div>
                    <div class="card-body">
                        <p class="card-text">(Earns 10-20 golds)</p>
                        <input type="hidden" name="farming" value="farm">
                        <button type="submit" class="btn btn-success">Find Gold!!!</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-3 mb-2">
            <form action="{% url 'gold:process' %}" method="POST">
                {% csrf_token %}
                <div class="card text-center">
                    <div class="card-header text-white bg-success">
                        <h4 class="card-title">Cave</h4>
                    </div>
                    <div class="card-body">
                        <p class="card-text">(Earns 5-10 golds)</p>
                        <input type="hidden" name="farming" value="cave">
                        <button type="submit" class="btn btn-success">Find Gold!!!</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-3 mb-2">
            <form action="{% url 'gold:process' %}" method="POST">
                {% csrf_token %}
                <div class="card text-center">
                    <div class="card-header text-white bg-success">
                        <h4 class="card-title">House</h4>
                    </div>
                    <div class="card-body">
                        <p class="card-text">(Earns 2-5 golds)</p>
                        <input type="hidden" name="farming" value="house">
                        <button type="submit" class="btn btn-success">Find Gold!!!</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-3 mb-2">
            <form action="{% url 'gold:process' %}" method="POST">
                {% csrf_token %}
                <div class="card text-center">
                    <div class="card-header text-white bg-success">
                        <h4 class="card-title">Casino</h4>
                    </div>
                    <div class="card-body">
                        <p class="card-text">(Earns/Takes 0-50 golds)</p>
                        <input type="hidden" name="farming" value="casino">
                        <button type="submit" class="btn btn-warning">Find Gold!!!</button>
                    </div>
                </div>
            </form>
        </div>        
    </div>
    <div class="row">
        <h4 class="text-light">Activities</h4>
        <div class="col-lg-12">
            <div class="card log">
                {% for log in request.session.log reversed %}
                {% if "lost" in log %}    
                    <h6 class="text-danger">{{ log }}</h6>
                {% else %}
                    <h6 class="text-success">{{ log }}</h6>
                {% endif %}
            {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

core/templates/lost.html
{% extends "base.html" %}
{% block title %}Ninja Gold - You Won!!!{% endblock %}
{% block header %}
<h2 class="text-light">You Lost :(</h2>
{% endblock %}
{% block subheader %}
<h3 class="text-warning">{{ request.session.gold }} golds in {{ request.session.count }} attempts</h3>
{% endblock %}
{% block content %}
<a href="{% url 'gold:reset' %}" class="btn btn-light">Play Again</a>
{% endblock %}

core/templates/win.html
{% extends "base.html" %}
{% block title %}Ninja Gold - You Won!!!{% endblock %}
{% block header %}
<h2 class="text-light">You Won!!!</h2>
{% endblock %}
{% block subheader %}
<h3 class="text-warning">{{ request.session.gold }} golds in {{ request.session.count }} attempts</h3>
{% endblock %}
{% block content %}
<a href="{% url 'gold:reset' %}" class="btn btn-light">Play Again</a>
{% endblock %}